services:
  - type: web
    name: intx-preevol-backend
    runtime: node
    rootDir: backend
    plan: starter
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.9.0
      - key: NODE_ENV
        value: production
      - key: OPENSSL_CONF
        value: /dev/null
      - key: DATABASE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PUBLIC_SERVER_FILE
        value: https://intx-preevol-backend.onrender.com/

  - type: web
    name: intx-preevol-frontend
    runtime: static
    rootDir: frontend
    plan: starter
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20.9.0
      - key: VITE_BACKEND_SERVER
        value: https://intx-preevol-backend.onrender.com
      - key: VITE_FILE_BASE_URL
        value: https://intx-preevol-backend.onrender.com
      - key: VITE_WEBSITE_URL
        value: https://intx-preevol-frontend.onrender.com
