export const fields = {
  enabled: { type: 'boolean', label: 'Enabled', defaultValue: true },
  company: { type: 'async', entity: 'company', displayLabels: ['name'], outputValue: '_id', required: true, disableForTable: true },
  companyName: { type: 'string', label: 'company', dataIndex: ['company', 'name'], disableForForm: true },
  type: { type: 'async', entity: 'type', displayLabels: ['typeName'], outputValue: '_id', disableForTable: true },
  typeNameRef: { type: 'string', label: 'type', dataIndex: ['type', 'typeName'], disableForForm: true },
  category: { type: 'async', entity: 'category', displayLabels: ['name'], outputValue: '_id', disableForTable: true },
  categoryNameRef: { type: 'string', label: 'category', dataIndex: ['category', 'name'], disableForForm: true },
  subCategory: { type: 'async', entity: 'subcategory', displayLabels: ['name'], outputValue: '_id', disableForTable: true },
  subCategoryNameRef: { type: 'string', label: 'subCategory', dataIndex: ['subCategory', 'name'], disableForForm: true },
  model: { type: 'async', entity: 'model', displayLabels: ['modelName'], outputValue: '_id', disableForTable: true },
  modelNameRef: { type: 'string', label: 'model', dataIndex: ['model', 'modelName'], disableForForm: true },
  plungerDia: { type: 'async', entity: 'plungerdia', displayLabels: ['plungerDiaName'], outputValue: '_id', disableForTable: true },
  plungerDiaNameRef: { type: 'string', label: 'plungerDia', dataIndex: ['plungerDia', 'plungerDiaName'], disableForForm: true },
  goodsName: { type: 'string', required: true },
  description: { type: 'textarea' },
  uom: { type: 'string' },
  hsn: { type: 'string' },
  gstRate: { type: 'number' },
  avgPricePerUnit: { type: 'number' },
  openingQty: { type: 'number' },
  reOrderLevel: { type: 'number' },
  legacyGoodsId: { type: 'number', label: 'Legacy Goods ID' },
  stockCategoryId: { type: 'number', label: 'Stock Category ID' },
  stockSubCategoryId: { type: 'number', label: 'Stock SubCategory ID' },
  closingQty: { type: 'number', label: 'Closing Qty' },
  closingStockVal: { type: 'number', label: 'Closing Stock Value' },
  fullGoodsName: { type: 'string', label: 'Full Goods Name' },
  lastUpdatedText: { type: 'string', label: 'Last Updated Text' },
};
